name: Test
on: [push]
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: List files in the repository
        run: |
          rake test
      - run: echo "This job's status is ${{ job.status }}."
